<?php

?>

<div id="co-billing-form">
    <h3><?php echo $this->__('Billing Information') ?></h3>
    <ul class="form-list">
        <?php if ($this->customerHasAddresses()): ?>
            <li class="wide">
                <label for="billing-address-select" class="notice">
                    <?php echo $this->__('Select a billing address from your address book or enter a new address.') ?>
                </label>

                <div class="input-box">
                    <?php echo $this->getAddressesHtmlSelect('billing'); ?>
                </div>
            </li>
        <?php endif; ?>
        <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
            <fieldset>
                <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>"
                       id="billing:address_id"/>
                <ul>
                    <li class="fields">
                        <?php
                        echo $this->getLayout()->createBlock('customer/widget_name')
                            ->setObject(
                                $this->getAddress()->getFirstName() ? $this->getAddress() :
                                    $this->getQuote()->getCustomer())
                            ->setForceCustomerRequiredAttributes(!$this->isCustomerLoggedIn())
                            ->setFieldIdFormat('billing:%s')
                            ->setFieldNameFormat('billing[%s]')
                            ->toHtml();
                        ?>
                    </li>
                    <li class="fields">
                        <div class="field">
                            <label for="billing:company"><?php echo $this->__('Company') ?></label>

                            <div class="input-box">
                                <?php $billingCompany = $this->escapeHtml($this->getAddress()->getCompany()); ?>
                                <input type="text" name="billing[company]" value="<?php echo $billingCompany; ?>"
                                       class="input-text"/>
                            </div>
                        </div>
                        <?php if (!$this->isCustomerLoggedIn()) : ?>
                            <div class="field">
                                <label for="billing:email"
                                       class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                                <?php $billingEmail = $this->escapeHtml($this->getAddress()->getEmail()); ?>
                                <input type="email" required="required" value="<?php echo $billingEmail; ?>"
                                       class="input-text"/>
                            </div>
                        <?php endif; ?>
                    </li>
                    <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                    <li class="wide">
                        <label for="billing:street1" class="required"><em>*</em><?php echo $this->__('Address') ?>
                        </label>

                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('Street Address') ?>"
                                   name="billing[street][]" id="billing:street1"
                                   value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>"
                                   class="input-text <?php echo $_streetValidationClass ?>"/>
                        </div>
                    </li>
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                        <li class="wide">
                            <div class="input-box">
                                <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>"
                                       name="billing[street][]" id="billing:street<?php echo $_i ?>"
                                       value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>"
                                       class="input-text <?php echo $_streetValidationClass ?>"/>
                            </div>
                        </li>
                    <?php endfor; ?>
                    <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                        <li class="wide">
                            <label for="billing:vat_id"><?php echo $this->__('VAT Number') ?></label>

                            <div class="input-box">
                                <input type="text" id="billing:vat_id" name="billing[vat_id]"
                                       value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>"
                                       title="<?php echo $this->__('VAT Number') ?>"
                                       class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>"/>
                            </div>
                        </li>
                    <?php endif; ?>
                    <li class="fields">
                        <div class="field">
                            <label for="billing:city" class="required"><em>*</em><?php echo $this->__('City') ?>
                            </label>

                            <div class="input-box">
                                <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]"
                                       value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"
                                       class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>"
                                       id="billing:city"/>
                            </div>
                        </div>
                        <div class="field">
                            <label for="billing:region_id"
                                   class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>

                            <div class="input-box">
                                <select id="billing:region_id" name="billing[region_id]"
                                        title="<?php echo $this->__('State/Province') ?>" class="validate-select"
                                        style="display:none;">
                                    <option
                                        value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                </select>
                                <script type="text/javascript">
                                    //<![CDATA[
                                    $('billing:region_id').setAttribute('defaultValue', "<?php echo $this->getAddress()->getRegionId() ?>");
                                    //]]>
                                </script>
                                <input type="text" id="billing:region" name="billing[region]"
                                       value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"
                                       title="<?php echo $this->__('State/Province') ?>"
                                       class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>"
                                       style="display:none;"/>
                            </div>
                        </div>
                    </li>
                    <li class="fields">
                        <div class="field">
                            <label for="billing:postcode"
                                   class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>

                            <div class="input-box">
                                <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>"
                                       name="billing[postcode]" id="billing:postcode"
                                       value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>"
                                       class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>"/>
                            </div>
                        </div>
                        <div class="field">
                            <label for="billing:country_id"
                                   class="required"><em>*</em><?php echo $this->__('Country') ?></label>

                            <div class="input-box">
                                <?php echo $this->getCountryHtmlSelect('billing') ?>
                            </div>
                        </div>
                    </li>
                    <li class="fields">
                        <div class="field">
                            <label for="billing:telephone"
                                   class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>

                            <div class="input-box">
                                <input type="text" name="billing[telephone]"
                                       value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>"
                                       title="<?php echo $this->__('Telephone') ?>"
                                       class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>"
                                       id="billing:telephone"/>
                            </div>
                        </div>
                        <div class="field">
                            <label for="billing:fax"><?php echo $this->__('Fax') ?></label>

                            <div class="input-box">
                                <input type="text" name="billing[fax]"
                                       value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>"
                                       title="<?php echo $this->__('Fax') ?>"
                                       class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>"
                                       id="billing:fax"/>
                            </div>
                        </div>
                    </li>
                </ul>
            </fieldset>
        </li>
        <?php if ($this->canShip()): ?>
            <li class="control">
                <input type="checkbox" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes"
                       value="1"<?php if ($this->isUseBillingAddressForShipping()) { ?> checked="checked"<?php } ?>
                       title="<?php echo $this->__('Ship to this address') ?>" class="checkbox   "/><label
                    for="billing:use_for_shipping_yes"><?php echo $this->__('Ship to this address') ?></label>
            </li>
        <?php endif; ?>
    </ul>
</div>
