<?php
$package = Mage::getDesign()->getPackageName();
$theme = Mage::getDesign()->getTheme('frontend');
$isPersistent = Mage::helper('bc_checkout')->isPersistentMember();
?>
<div class="opc-wrapper-opc design_package_<?php echo $package; ?> design_theme_<?php echo $theme; ?>">
    <h2><?php printf($this->__('Checkout on %s'), Mage::app()->getStore()->getFrontendName()); ?></h2>

    <div class="opc-menu">
        <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
            <p class="left"><a href="<?php echo Mage::helper('bc_checkout/url')->getLoginUrl(); ?>"
                               class="signin-modal opc-login-trigger " data-moda="modal-login">LOGIN</a></p>
        <?php endif; ?>
        <div class="right review-menu-block">
            <a class="review-total" title="<?php echo $this->__('Grand total'); ?>">
                <i class="fa fa-2x fa-shopping-cart"></i>
                <span class="price"><span
                        class="price"><?php echo Mage::helper('bc_checkout')->getGrandTotal(); ?></span></span>
            </a>
        </div>
    </div>
    <div class="clear"></div>
    <div <?php if ($is_persistent): ?>style="display:none !important;"<?php endif; ?>>
        <div class="opc-col-left">
            <form id="opc-address-form-billing" method="post">
                <?php echo $this->getChildHtml('billing'); ?>
            </form>
            <?php #echo $this->getChildHtml('shipping'); ?>
        </div>
        <div class="opc-col-center">
            <?php if (!Mage::getSingleton('checkout/type_onepage')->getQuote()->isVirtual()) : ?>
                <div class="shipping-block">
                    <h3><?php echo $this->__('Shipping method'); ?></h3>

                    <div class="shipping-block-methods">
                        <?php echo $this->getChildHtml('shipping_method'); ?>
                    </div>
                </div>
            <?php endif; ?>
        </div>
        <div class="opc-col-right">
            <div class="payment-block">
                <h3><?php echo $this->__('Payment Method')?></h3>
                <?php echo $this->getChildHtml('payment');?>
            </div>
            <div class="opc-review-actions" id="checkout-review-submit">
                <h5 class="grand_total"><?php echo $this->__('Grand Total')?><?php echo Mage::helper('bc_checkout')->getGrandTotal()?></h5>
                <?php #echo $this->getChildHtml('agreements')?>
                <?php #echo $this->getChildHtml('opc.newsletters');?>
                <button type="button" title="<?php echo $this->__('Place Order Now') ?>" class="button btn-checkout opc-btn-checkout"><span><span><?php echo $this->__('Place Order Now') ?></span></span></button>
            </div>
        </div>
    </div>
</div>